baseURL = "https://devpoga.org/"
languageCode = "en-us"
title = "Dev.Poga"
paginate = 15

theme = "arabica"

hasCJKLanguage = true

[params]
    description = ""
    dateFormatToUse = "2006-01-02"

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
