baseURL = "https://devpoga.org/"
languageCode = "en-us"
title = "Dev.Poga"

theme = "hugo-bearblog"

hasCJKLanguage = true

timeZone = "Asia/Taipei"

[params]
    paginate = 15
    description = ""
    dateFormatToUse = "2006-01-02"

[markup.goldmark.renderer]
unsafe= true

