baseURL = "https://devpoga.org/"
languageCode = "en-us"
title = "Dev.Poga"

theme = "hugo_theme_pickles"

hasCJKLanguage = true

[params]
    paginate = 15
    description = ""
    dateFormatToUse = "2006-01-02"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

