baseURL = "https://devpoga.org/"
languageCode = "en-us"
title = "Dev.Poga"
paginate = 15

theme = "arabica"

hasCJKLanguage = true

[params]
    description = "A non-leaky bucket"
    dateFormatToUse = "2006-01-02"

[markup.goldmark.renderer]
unsafe= true

