baseURL = "https://devpoga.org/"
languageCode = "en-us"
title = "Dev.Poga"
paginate = 15

theme = "arabica"

hasCJKLanguage = true

[params]
    description = ""
    dateFormatToUse = "2006-01-02"
    twitter = "devpoga"
